### ISSUE TITLE
Is it possible to generate the language-contribution.ts file?

### ISSUE THREAD

**Issue by ghost** [TypeFox/theia-xtext#12]
I am using this project as template for my own xtext dsl theia extension.
In order to do so i am currently facing the problem that the keyword auto suggestion is not working.

Maybe i have something done wrong in the ./xtext-dsl-extension/src/browser/language-contribution.ts file?

Is it possible to generate the language-contribution.ts file?

**Comment by cdietrich** [comment]
there is no fragment yet but its possible for sure (if you find good conventions)
